# Generated by Django 4.0.4 on 2022-06-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cautare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produs', models.CharField(max_length=100)),
                ('descriere_si_pret', models.CharField(max_length=100)),
                ('magazin', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=1)),
            ],
        ),
    ]
