# Generated by Django 4.0.4 on 2022-06-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cautare',
            name='cod_produs',
        ),
    ]
