# Generated by Django 4.0.4 on 2022-06-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produse',
            name='url_emag',
            field=models.URLField(blank=True, null=True),
        ),
    ]
