# Generated by Django 4.0.4 on 2022-06-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_remove_cautare_cod_produs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cautare',
            name='cod_produs',
            field=models.CharField(default='cod_produs', max_length=100),
            preserve_default=False,
        ),
    ]
