# Generated by Django 4.0.4 on 2022-06-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_cautare_cod_produs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cautare',
            name='rezultat',
            field=models.CharField(default='rezultat', max_length=100),
            preserve_default=False,
        ),
    ]
