# Generated by Django 4.0.4 on 2022-06-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_cautare_rezultat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cautare',
            name='rezultat',
        ),
    ]
