# Generated by Django 4.0.4 on 2022-06-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_remove_cautare_rezultat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cautare',
            name='cautare',
            field=models.CharField(default='cautare', max_length=100),
            preserve_default=False,
        ),
    ]
