# Generated by Django 4.0.4 on 2022-06-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='cautare',
            name='aaa',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
    ]
