# Generated by Django 4.0.4 on 2022-06-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_produse_delete_cautare_delete_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produse',
            old_name='descriere',
            new_name='descriere_altex',
        ),
        migrations.AddField(
            model_name='produse',
            name='descriere_emag',
            field=models.CharField(default='descriere_altex', max_length=100),
            preserve_default=False,
        ),
    ]
