# Generated by Django 4.0.4 on 2022-06-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_rename_descriere_produse_descriere_altex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produse',
            name='descriere_altex',
        ),
        migrations.RemoveField(
            model_name='produse',
            name='descriere_emag',
        ),
    ]
