# Generated by Django 4.0.4 on 2022-06-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_remove_produse_descriere_altex_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produse',
            old_name='magazin',
            new_name='descriere',
        ),
    ]
