# Generated by Django 4.0.4 on 2022-06-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_rename_magazin_produse_descriere'),
    ]

    operations = [
        migrations.AddField(
            model_name='produse',
            name='status_stoc_altex',
            field=models.CharField(default='status_stoc_altex', max_length=100),
            preserve_default=False,
        ),
    ]
