# Generated by Django 4.0.4 on 2022-06-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_produse_status_stoc_altex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produse',
            name='status_stoc_altex',
        ),
    ]
