# Generated by Django 4.0.4 on 2022-06-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_remove_produse_status_stoc_altex'),
    ]

    operations = [
        migrations.AddField(
            model_name='produse',
            name='imagine_altex',
            field=models.ImageField(default='imagine_altex', height_field=100, upload_to=None, width_field=100),
            preserve_default=False,
        ),
    ]
