# Generated by Django 4.0.4 on 2022-06-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_produse_imagine_altex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produse',
            name='imagine_altex',
        ),
        migrations.AddField(
            model_name='produse',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
