# Generated by Django 4.0.4 on 2022-06-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_remove_produse_imagine_altex_produse_imagine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produse',
            name='imagine',
        ),
    ]
