# Generated by Django 4.0.4 on 2022-06-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0017_remove_produse_imagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='produse',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
