# Generated by Django 4.0.4 on 2022-06-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0018_produse_imagine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produse',
            old_name='pret_altex',
            new_name='pret_altex2',
        ),
    ]
