# Generated by Django 4.0.4 on 2022-06-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0019_rename_pret_altex_produse_pret_altex2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produse',
            old_name='pret_altex2',
            new_name='pret_altex',
        ),
    ]
